name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: laytan/setup-odin@v2
        with:
          release: dev-2026-05
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ./build.sh

      - name: Test
        run: odin test src -collection:lib=lib
